# Generated by Django 5.0 on 2023-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForwardPhysicalValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prod", models.CharField(max_length=250, null=True)),
                ("mar", models.CharField(max_length=250, null=True)),
                ("apr", models.CharField(max_length=250, null=True)),
                ("may", models.CharField(max_length=250, null=True)),
                ("q3", models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
