# Generated by Django 5.0 on 2023-12-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeaborneLastTradedLevels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=250, null=True)),
                ("primary", models.CharField(max_length=250, null=True)),
                ("secondary", models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
