# Generated by Django 4.2.8 on 2024-01-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seabornelasttradedlevels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardPhysicalTextCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
